//! `.BUILDINFO` generator.
//!
//! Records build environment details for reproducibility and auditing:
//! packager identity, build date, toolchain versions, build directory,
//! and environment flags used during compilation.

use crate::config::XpkgConfig;
use crate::recipe::Recipe;

/// Generate the `.BUILDINFO` file content.
pub fn generate_buildinfo(recipe: &Recipe, config: &XpkgConfig) -> String {
    let pkg = &recipe.package;
    let mut out = String::new();

    // Header.
    out.push_str("# Generated by xpkg\n");

    // Package identity.
    out.push_str(&format!("pkgname = {}\n", pkg.name));
    out.push_str(&format!("pkgver = {}-{}\n", pkg.version, pkg.release));

    // Build environment.
    out.push_str(&format!("builddate = {}\n", current_timestamp()));
    out.push_str(&format!(
        "builddir = {}\n",
        config.options.builddir.display()
    ));
    out.push_str(&format!("buildtool = xpkg {}\n", env!("CARGO_PKG_VERSION")));

    // System info.
    if let Ok(hostname) = std::env::var("HOSTNAME") {
        out.push_str(&format!("buildhost = {hostname}\n"));
    }

    // Environment flags.
    let env = &config.environment;
    if !env.cflags.is_empty() {
        out.push_str(&format!("CFLAGS = {}\n", env.cflags));
    }
    if !env.cxxflags.is_empty() {
        out.push_str(&format!("CXXFLAGS = {}\n", env.cxxflags));
    }
    if !env.ldflags.is_empty() {
        out.push_str(&format!("LDFLAGS = {}\n", env.ldflags));
    }
    if !env.makeflags.is_empty() {
        out.push_str(&format!("MAKEFLAGS = {}\n", env.makeflags));
    }

    // Compression settings.
    out.push_str(&format!("compress = {}\n", config.options.compress));
    out.push_str(&format!(
        "compress_level = {}\n",
        config.options.compress_level
    ));

    out
}

/// Current Unix timestamp in seconds.
fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::recipe::{BuildSection, DependencySection, PackageSection, Recipe, SourceSection};

    fn test_recipe() -> Recipe {
        Recipe {
            package: PackageSection {
                name: "test-pkg".into(),
                version: "2.0".into(),
                release: 3,
                description: "Test".into(),
                url: None,
                license: vec![],
                arch: vec!["x86_64".into()],
                provides: vec![],
                conflicts: vec![],
                replaces: vec![],
            },
            dependencies: DependencySection::default(),
            source: SourceSection::default(),
            build: BuildSection::default(),
        }
    }

    #[test]
    fn test_buildinfo_contains_package_identity() {
        let info = generate_buildinfo(&test_recipe(), &XpkgConfig::default());
        assert!(info.contains("pkgname = test-pkg\n"));
        assert!(info.contains("pkgver = 2.0-3\n"));
    }

    #[test]
    fn test_buildinfo_contains_buildtool() {
        let info = generate_buildinfo(&test_recipe(), &XpkgConfig::default());
        assert!(info.contains("buildtool = xpkg "));
    }

    #[test]
    fn test_buildinfo_contains_environment_flags() {
        let config = XpkgConfig::default();
        let info = generate_buildinfo(&test_recipe(), &config);
        assert!(info.contains("CFLAGS = -march=x86-64 -O2 -pipe\n"));
        assert!(info.contains("CXXFLAGS = -march=x86-64 -O2 -pipe\n"));
        assert!(info.contains("MAKEFLAGS = -j$(nproc)\n"));
    }

    #[test]
    fn test_buildinfo_omits_empty_ldflags() {
        let config = XpkgConfig::default();
        let info = generate_buildinfo(&test_recipe(), &config);
        assert!(!info.contains("LDFLAGS"));
    }

    #[test]
    fn test_buildinfo_contains_compression() {
        let info = generate_buildinfo(&test_recipe(), &XpkgConfig::default());
        assert!(info.contains("compress = zstd\n"));
        assert!(info.contains("compress_level = 19\n"));
    }
}
