//! `.PKGINFO` generator.
//!
//! Produces the package information file that contains identity, version,
//! description, dependencies, and installed size. This is the primary
//! metadata file read by the package manager during installation.
//!
//! Format: one `key = value` pair per line, comments start with `#`.

use std::path::Path;

use crate::error::XpkgResult;
use crate::recipe::Recipe;

/// Generate the `.PKGINFO` file content from a recipe and the populated PKGDIR.
pub fn generate_pkginfo(recipe: &Recipe, pkgdir: &Path) -> XpkgResult<String> {
    let pkg = &recipe.package;
    let deps = &recipe.dependencies;
    let size = calculate_installed_size(pkgdir);

    let mut out = String::new();

    // Header comment.
    out.push_str("# Generated by xpkg\n");
    out.push_str(&format!("# using xpkg v{}\n", env!("CARGO_PKG_VERSION")));

    // Required fields.
    out.push_str(&format!("pkgname = {}\n", pkg.name));
    out.push_str(&format!("pkgver = {}-{}\n", pkg.version, pkg.release));
    out.push_str(&format!("pkgdesc = {}\n", pkg.description));

    if let Some(ref url) = pkg.url {
        out.push_str(&format!("url = {url}\n"));
    }

    out.push_str(&format!("builddate = {}\n", current_timestamp()));
    out.push_str(&format!("size = {size}\n"));

    for arch in &pkg.arch {
        out.push_str(&format!("arch = {arch}\n"));
    }

    for lic in &pkg.license {
        out.push_str(&format!("license = {lic}\n"));
    }

    // Provides, conflicts, replaces.
    for p in &pkg.provides {
        out.push_str(&format!("provides = {p}\n"));
    }
    for c in &pkg.conflicts {
        out.push_str(&format!("conflict = {c}\n"));
    }
    for r in &pkg.replaces {
        out.push_str(&format!("replaces = {r}\n"));
    }

    // Dependencies.
    for dep in &deps.depends {
        out.push_str(&format!("depend = {dep}\n"));
    }
    for dep in &deps.makedepends {
        out.push_str(&format!("makedepend = {dep}\n"));
    }
    for dep in &deps.checkdepends {
        out.push_str(&format!("checkdepend = {dep}\n"));
    }
    for dep in &deps.optdepends {
        out.push_str(&format!("optdepend = {dep}\n"));
    }

    Ok(out)
}

/// Calculate the total installed size of all files in PKGDIR (in bytes).
fn calculate_installed_size(pkgdir: &Path) -> u64 {
    if !pkgdir.exists() {
        return 0;
    }
    walk_size(pkgdir)
}

/// Recursively sum file sizes.
fn walk_size(dir: &Path) -> u64 {
    let mut total = 0u64;
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_symlink() {
                // Symlinks have no size contribution.
                continue;
            } else if path.is_dir() {
                total += walk_size(&path);
            } else if let Ok(meta) = path.metadata() {
                total += meta.len();
            }
        }
    }
    total
}

/// Current Unix timestamp in seconds.
fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::recipe::{BuildSection, DependencySection, PackageSection, Recipe, SourceSection};

    fn test_recipe() -> Recipe {
        Recipe {
            package: PackageSection {
                name: "hello".into(),
                version: "1.0".into(),
                release: 1,
                description: "Hello world program".into(),
                url: Some("https://example.com/hello".into()),
                license: vec!["MIT".into()],
                arch: vec!["x86_64".into()],
                provides: vec![],
                conflicts: vec![],
                replaces: vec![],
            },
            dependencies: DependencySection {
                depends: vec!["glibc".into()],
                makedepends: vec!["gcc".into()],
                checkdepends: vec![],
                optdepends: vec!["gettext: NLS support".into()],
            },
            source: SourceSection::default(),
            build: BuildSection::default(),
        }
    }

    #[test]
    fn test_pkginfo_contains_required_fields() {
        let tmp = tempfile::tempdir().unwrap();
        let pkgdir = tmp.path();
        std::fs::write(pkgdir.join("hello"), "binary").unwrap();

        let info = generate_pkginfo(&test_recipe(), pkgdir).unwrap();
        assert!(info.contains("pkgname = hello\n"));
        assert!(info.contains("pkgver = 1.0-1\n"));
        assert!(info.contains("pkgdesc = Hello world program\n"));
        assert!(info.contains("url = https://example.com/hello\n"));
        assert!(info.contains("arch = x86_64\n"));
        assert!(info.contains("license = MIT\n"));
    }

    #[test]
    fn test_pkginfo_contains_dependencies() {
        let tmp = tempfile::tempdir().unwrap();
        let info = generate_pkginfo(&test_recipe(), tmp.path()).unwrap();
        assert!(info.contains("depend = glibc\n"));
        assert!(info.contains("makedepend = gcc\n"));
        assert!(info.contains("optdepend = gettext: NLS support\n"));
    }

    #[test]
    fn test_pkginfo_calculates_size() {
        let tmp = tempfile::tempdir().unwrap();
        let pkgdir = tmp.path();
        std::fs::write(pkgdir.join("file1"), "hello").unwrap();
        std::fs::create_dir_all(pkgdir.join("subdir")).unwrap();
        std::fs::write(pkgdir.join("subdir/file2"), "world!").unwrap();

        let info = generate_pkginfo(&test_recipe(), pkgdir).unwrap();
        // "hello" = 5 bytes, "world!" = 6 bytes = 11 total
        assert!(info.contains("size = 11\n"));
    }

    #[test]
    fn test_pkginfo_empty_pkgdir_has_zero_size() {
        let tmp = tempfile::tempdir().unwrap();
        let info = generate_pkginfo(&test_recipe(), tmp.path()).unwrap();
        assert!(info.contains("size = 0\n"));
    }

    #[test]
    fn test_pkginfo_contains_provides_conflicts_replaces() {
        let tmp = tempfile::tempdir().unwrap();
        let mut recipe = test_recipe();
        recipe.package.provides = vec!["hello-bin".into()];
        recipe.package.conflicts = vec!["hello-git".into()];
        recipe.package.replaces = vec!["hello-old".into()];

        let info = generate_pkginfo(&recipe, tmp.path()).unwrap();
        assert!(info.contains("provides = hello-bin\n"));
        assert!(info.contains("conflict = hello-git\n"));
        assert!(info.contains("replaces = hello-old\n"));
    }
}
